name: Continuous Integration

on:
  push:
  pull_request:
    types:
      - opened
      - synchronize
    branches:
      - main

jobs:
  continuous-integration:
    name: Continuous Integration
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
    
      - name: Checkout
        uses: actions/checkout@v4

      - name: HashiCorp - Setup Terraform
        uses: hashicorp/setup-terraform@v4.0.0
        with:
          terraform_version: 1.14.8

      - name: Terraform fmt
        id: fmt
        run: terraform fmt -check
        continue-on-error: false
      
      - name: Install TFLint
        uses: terraform-linters/setup-tflint@v4
        with:
          tflint_version: v0.61.0

      - name: Init TFLint
        run: tflint --init

      - name: Check linting of Terraform files
        id: lint
        run: tflint

      - name: Terraform Init
        id: init
        run: terraform init
      
      - name: Terraform Validate
        id: validate
        run: terraform validate -no-color

      - name: Trivy Security Scan
        uses: aquasecurity/trivy-action@master
        with:
          scan-type: config
          scan-ref: .
          exit-code: 1

  documentation:
    needs: continuous-integration
    name: Documentation
    runs-on: ubuntu-latest
    permissions:
      contents: write
    if: ${{ github.base_ref == 'main' }}
    steps:
      
      - name: Checkout
        uses: actions/checkout@v4
        with:
          ref: ${{ github.event.pull_request.head.ref }}

      - name: HashiCorp - Setup Terraform
        uses: hashicorp/setup-terraform@v4.0.0
        with:
          terraform_version: 1.14.8
      
      - name: Render terraform docs and push changes back to PR
        uses: terraform-docs/gh-actions@v1.4.1
        with:
          working-dir: .
          output-file: README.md
          output-method: inject
          git-push: "true"
          git-push-user-name: "github-actions"
          git-push-user-email: "github-actions@github.com"
          git-commit-message: "docs(terraform): generated terraform docs [skip ci]"
